before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
before_script:
  - cp .sample.env .env
  
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  campfire:
    on_failure:
      - always
    on_success:
      - change
    template:
      - '(%{branch} - %{author}): %{message} - %{build_url}'
  email:
    - false
rvm:
  - 2.1.2
addons:
  postgresql: "9.3"
