default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || 'adf9asdgfuobasdfiba8dsf0zplbq'%>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
