Email:
  tag_attributes:
    type: email
    default: ""
Copyright:
  tag_attributes:
    type: text
    class: tinymce
    default: ""
About:
  tag_attributes:
    type: text
    class: tinymce
    default: ""
Home:
  tag_attributes:
    type: text
    class: tinymce
    default: ""
Help:
  tag_attributes:
    type: text
    class: tinymce
    default: ""
Title:
  tag_attributes:
    type: string
    default: ""
