production:
  solr:
    hostname: <%= ENV['ARTWALK_SOLR_URL'] ? ENV['ARTWALK_SOLR_URL'].split('/')[2].split(":").first || "localhost" : 'localhost' %>
    port: <%= ENV['ARTWALK_SOLR_URL'] ? ENV['ARTWALK_SOLR_URL'].split('/')[2].split(":").last : 8983%>
    log_level: WARNING
    path: <%= ENV['ARTWALK_SOLR_URL'] ? ("/" + ENV['ARTWALK_SOLR_URL'].split('/')[3..-1].join("/")) : '/solr/blacklight-core' %>
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight-core

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core-test

staging:
  solr:
    hostname: <%= ENV['ARTWALK_SOLR_URL'] ? ENV['ARTWALK_SOLR_URL'].split('/')[2].split(":").first || "localhost" : 'localhost' %>
    port: <%= ENV['ARTWALK_SOLR_URL'] ? ENV['ARTWALK_SOLR_URL'].split('/')[2].split(":").last : 8983%>
    log_level: WARNING
    path: <%= ENV['ARTWALK_SOLR_URL'] ? ("/" + ENV['ARTWALK_SOLR_URL'].split('/')[3..-1].join("/")) : '/solr/blacklight-core' %>
    # read_timeout: 2
    # open_timeout: 0.5
